### ISSUE TITLE
Embed block

### ISSUE THREAD

**Issue by jonatan-lledo-netcentric** [hlxsites/vg-roadchoice-com#146]
a block that popups an overlay to show a video

as an example:
https://roadchoice.com/about

TBR

**Comment by Gonzalo-CG** [comment]
### Business Value
As a content editor, I want a simple and straightforward way to embed YouTube videos on pages to easily add media content to the site.

### Description
A new block called Embed will be developed so that authors can embed YouTube videos on the site.

### Acceptance Criteria

- [ ] The Embed block is available for editors/content authors to use.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, closing the ticket
