### ISSUE TITLE
Bug: Major - Product detail images are not always displaying properly

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-roadchoice-com#202]
There seems to be a bug for some Road Choice part images in the product detail page as seen in the screen shot below. The image loads as expected in the [search results](https://www.roadchoice.com/search/?q=TUR1080003&st=parts&make=null&model=null), but then when the user clicks on the [product part detail page](https://www.roadchoice.com/parts?category=turbos&sku=TUR1080003), they no longer see the shield image and instead see an error. 

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/91b51cc6-0048-4dda-9996-8b76d35ecf93)

Another example where the first image isn't showing up - 

https://www.roadchoice.com/parts?category=shoes&sku=BKE1308EHD23

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/778e5a18-c592-4ff8-a547-d580a3dadb20)

**Comment by girishdigrajkar** [comment]
Hi @SantiagoHomps-NC :  Retest failed for one scenario hence, reopening the bug.
For the first scenario the bug is still reproducible with product number **TUR1080003R**  

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/b432bdaa-935a-41f9-aa23-825f4aaf7057">

For the second scenario, it works fine now :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/24ea8195-526c-4c53-b0f5-c31bcf6979c0">

**Comment by jonatan-lledo-netcentric** [comment]
@girishdigrajkar I uploaded the image to SharePoint and I updated the road-choice-website-images.xlsx related to the product TUR1080003R so now works. If any other image is available but the URL is broken, this could be a way to fix it without any further development.

Please, retest again. thanks

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct result hence, bug could be closed :
Hi @ZoeBeykirch : Assigning it to you for your validation and further closure:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/9d51303d-e986-423f-99d1-734dc8b490c0">

**Comment by ZoeBeykirch** [comment]
Seems to be working as expected now! Thank you!
