### ISSUE TITLE
Bug: Major - Duplicate part number search results

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-roadchoice-com#214]
On the roadchoice.com site, when the user searches in the part number search bar, there are some duplicate results coming up. For example, the part number CAC41115 should only show 1 result when the user searches it, however currently 18 are showing in the results. 

Link: https://www.roadchoice.com/search/?q=RC%20CAC41115&st=parts&make=null&model=null 

Data File: https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B48FEADC4-AF85-4375-B1F8-9C90770645E4%7D&file=rc-charge-air-coolers.xlsx&action=default&mobileredirect=true 

Another example is part number SW825225H5 which shows 2 search results when there should only be 1.

**Comment by jonatan-lledo-netcentric** [comment]
> On the roadchoice.com site, when the user searches in the part number search bar, there are some duplicate results coming up. For example, the part number CAC41115 should only show 1 result when the user searches it, however currently 18 are showing in the results.
> 
> Link: https://www.roadchoice.com/search/?q=RC%20CAC41115&st=parts&make=null&model=null

In the file, there are 18 rows with the only difference being the model. If the requirement is that if a product share the Part Number with other models the results has to show only 1, please confirm it to update the search to reflect that CR
<img width="1692" alt="Screenshot 2023-11-06 at 09 24 37" src="https://github.com/hlxsites/vg-roadchoice-com/assets/117984204/18544ec8-250e-4887-817d-3404c72559cf">



> Data File: [https://adobe.sharepoint.com/❌/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B48FEADC4-AF85-4375-B1F8-9C90770645E4%7D&file=rc-charge-air-coolers.xlsx&action=default&mobileredirect=true](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B48FEADC4-AF85-4375-B1F8-9C90770645E4%7D&file=rc-charge-air-coolers.xlsx&action=default&mobileredirect=true)
> 
> Another example is part number SW825225H5 which shows 2 search results when there should only be 1.

for this example, we use subcategory files to show the info on the subcategory page and on the PDP pages. so having one using a Main Category instead of a Subcategory is not considered in the code, in this case, maybe it would be good if the line that has the Main category could be removed


<img width="1694" alt="Screenshot 2023-11-06 at 09 44 27" src="https://github.com/hlxsites/vg-roadchoice-com/assets/117984204/6fb7091b-09fc-41ae-87cc-773960288957">

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking defect to done status:
1. For part number CAC41115 :  Only one result is displayed as expected : 
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/abc5e1b9-5fc5-4ac2-87cb-ae98f8463aa6)

2. For part number SW825225H5 : only first record is being displayed as expected :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/33f9d69f-c459-4ce2-8510-02d3dea6991c">
