### ISSUE TITLE
Bug: Medium: Buttons/Links are not opening in a new tab

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-roadchoice-com#224]
**Bug steps:** 
1. View any blog article on https://www.roadchoice.com/ 
2. When a user clicks on any button/link in the article, it opens in the same tab window. 

**Expectation:** 
When a user clicks on any button/link, it should open in a new tab so that the user can view both pages separately on their browser window.

**Examples:** 
Blog 1: https://www.roadchoice.com/blog/a-smooth-ride-for-your-driveline
Blog 2: https://www.roadchoice.com/blog/3-reasons-to-practice-suspension-preventative-maintenance
Part Category Page: https://www.roadchoice.com/part-category/chemicals-and-lubricants
All links in the Part Category Page example open in a new tab except in "Pick the right coolant for you" button.  
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/09732bcb-b509-4fc1-b4ca-03eab239ff1b)

**Additional Steps:** 
As a content editor, we have tried to update the links using the Word desktop app to select the option to open in a new tab, and that did not resolve this bug. This should be the default setting for all new buttons/links to open in a new tab. 
 ![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/c87e0a18-7e35-4485-acd5-8a3057458828)

**Comment by SantiagoHomps-NC** [comment]
@varunmitra please check this [link](https://main--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/link-test/)

I added at the end 2 types of links and how they should behave

**Comment by Varunvolvo** [comment]
We have checked it from our end and we found out that all the document/media links are opening the new tab. When it is been linked to any of the page (product page) then the button/link is opening in the same window. We tried to change it and that seems to be something which is set default. 

More examples - 

https://www.roadchoice.com/part-category/drivetrain

https://www.roadchoice.com/part-category/wheel-end

Even in these pages the we have links/buttons which are opening up in same tab because of the same issue. 

So, we might need more help here since this is not something that we are able to change or update. 

Thanks, 
Varun

**Comment by SantiagoHomps-NC** [comment]
@varunmitra all internal links will open in the same tab and all external links and documents will open in a new one, this is the default behaviour. The only exception to this is adding `[new-tab] `written before the text link (it will be deleted afterwards). If you are trying to set this new tab configuration in the the MS Word it wont work. Please check the link I sent in the comment above.

**Comment by BeckyMedlin** [comment]
@janedbarra Closing as completed per @Varunvolvo 's comment from February. Please let me know if this is still a problem.
