### ISSUE TITLE
FR: Subcategory Template: Total number and page navigation

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-roadchoice-com#38]

**Comment by shirin27** [comment]
**Description**

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/83ef23e4-b21c-4cb5-8925-9c9bb46cd4bd)

**Acceptance criteria**
- A max of 12 items is displayed per page
- A max of 7 individual pages are displayed in the pagination
- Navigation arrows are available for next or previous page, but also for first and last page
- Text for total number: "Showing <ord. of first element - ord. of last element> of <total number> items"

**Open point**
- On the current website, pagination breaks on small viewports; should we try to make the max number of pages dynamically determined, based on the width of the viewport?



![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/135319298/343c2987-ae9a-4cd9-b525-5d7c1ef8300f)

**Comment by shirin27** [comment]
To be done after https://github.com/hlxsites/vg-roadchoice-com/issues/36 (at least for testing reasons)

**Comment by Gonzalo-CG** [comment]
### Update
Instead of the proposed pagination navigation, we will take a "load more" approach to display items, where initially up to 12 items are rendered, and upon clicking a "Show More" button up to 12 more items are rendered below for each click of the button.

### New Acceptance Criteria (please ignore previous ones)
- [ ] A max of 12 items are displayed initially.
- [ ] Text for number of results: "Showing top <no. of loaded items> results"
- [ ] A "Show More" button is present both on top and at the bottom of the results.
- [ ] The "Show More" buttons load up to 12 more items per click below the initial ones.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the ticket to done status:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/1a4d4cf2-aa00-4c3a-a073-c1d1495e5b87">
