### ISSUE TITLE
FR: Change Twitter social media icon

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-roadchoice-com#98]
Update the Twitter social media icon 

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/2a6cfe2a-9e26-4d88-8754-d9d30e4f9f9a)

in the footer to new icon attached here (no asset preview due to white text on clear background)

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/125895595/7c9325dc-a307-44f4-a579-5713bd0d59d4)

**Comment by Gonzalo-CG** [comment]
### **Description**

Since Twitter is now called X, the social media icon on the footer has to be replaced with the new X icon (attached above by Zoe)

### **Acceptance Criteria**

- [ ] 1. The Twitter icon present on the footer is replaced by the new X icon. 

![Image](https://github.com/hlxsites/vg-roadchoice-com/assets/139977780/2130fecf-dad1-4055-ad27-ebd6de0f3a72)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the ticket to done.
